<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date_end</name>
   <tag></tag>
   <elementGuidId>147dabd5-7134-4ed5-bfa2-74c8accdefbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,&quot;edit-form-column-1322&quot;)]//*[contains(@class,&quot;editable-date&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit-control ng-pristine ng-untouched ng-valid ng-isolate-scope ng-empty ng-valid-datetime editable</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datetime-picker</name>
      <type>Main</type>
      <value>dd.MM.yyyy HH:mm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>editWorker.Row[column.Id]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!column.IsEditable || isReadOnly</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{editable:(column.IsEditable &amp;&amp; !isReadOnly)}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is-open</name>
      <type>Main</type>
      <value>editWorker.datePickerOpened[column.Id]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datepicker-append-to-body</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>button-bar</name>
      <type>Main</type>
      <value>editWorker.datePickerButtons</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datepicker-options</name>
      <type>Main</type>
      <value>editWorker.datepickerOptions</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>timepicker-options</name>
      <type>Main</type>
      <value>editWorker.timepickerOptions</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;modal app-modal-window fade ng-scope ng-isolate-scope in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ng-scope&quot;]/div[1]/div[1]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;editRowBody&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;padded edit-form ng-scope&quot;]/div[@class=&quot;row ng-scope&quot;]/div[@class=&quot;edit-form-column-1322 col-md-4 vbottom&quot;]/ng-html-include[@class=&quot;ng-scope&quot;]/div[@class=&quot;editable-date ng-scope&quot;]/input[@class=&quot;edit-control ng-pristine ng-untouched ng-valid ng-isolate-scope ng-empty ng-valid-datetime editable&quot;]</value>
   </webElementProperties>
</WebElementEntity>
