<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Choose_integer</name>
   <tag></tag>
   <elementGuidId>5e7b1443-4285-41e5-a197-f572dddf5775</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[count(. | //*[@class = 'ui-select-choices-row-inner']) = count(//*[@class = 'ui-select-choices-row-inner'])][count(. | id(&quot;ui-select-choices-row-0-2&quot;)/span[@class=&quot;ui-select-choices-row-inner&quot;]) = count(id(&quot;ui-select-choices-row-0-2&quot;)/span[@class=&quot;ui-select-choices-row-inner&quot;])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@ng-model,&quot;selectedNode.DisplayType&quot;)]//ul/li/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-select-choices-row-inner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-select-choices-row-0-2&quot;)/span[@class=&quot;ui-select-choices-row-inner&quot;]</value>
   </webElementProperties>
</WebElementEntity>
