<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Span_field_types</name>
   <tag></tag>
   <elementGuidId>121cb672-2121-4b44-b453-a851fd769a40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@ng-model,&quot;selectedNode.DisplayType&quot;)]//span[contains(@class, &quot;btn-default&quot;)][contains(@class, &quot;ui-select-toggle&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default form-control ui-select-toggle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select box activate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>$select.disabled</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$select.activate()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blockContainer&quot;)/div[@class=&quot;inner-flex ng-scope&quot;]/div[@class=&quot;inner-flex-stretch&quot;]/div[@class=&quot;panel panel-default inner-flex&quot;]/div[@class=&quot;panel-body padded inner-flex-stretch inner-flex&quot;]/div[@class=&quot;inner-flex-stretch inner-flex ng-scope&quot;]/div[@class=&quot;inner-flex inner-flex-stretch ng-scope&quot;]/div[@class=&quot;row inner-flex-stretch&quot;]/div[@class=&quot;col-md-7 inner-flex&quot;]/div[@class=&quot;panel panel-info inner-flex-stretch&quot;]/div[@class=&quot;panel-body&quot;]/div[1]/div[1]/div[1]/table[@class=&quot;table table-hover&quot;]/tbody[2]/tr[1]/td[2]/div[@class=&quot;max-width ui-select-container ui-select-bootstrap dropdown ng-pristine ng-valid ng-scope ng-not-empty ng-touched&quot;]/div[@class=&quot;ui-select-match ng-scope btn-default-focus&quot;]/span[@class=&quot;btn btn-default form-control ui-select-toggle&quot;]</value>
   </webElementProperties>
</WebElementEntity>
