<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>stngs</name>
   <tag></tag>
   <elementGuidId>12ae3371-6a8d-4f28-9a28-9e1836159061</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;blockContainer&quot;]/div/div/div/div[2]/div/div[2]/div[2]/div[2]/div/div/div/div/div/table/tbody[7]/tr/th/a
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
